// This file will be auto-generated by Supabase CLI
// For now, you can use this placeholder or generate types with: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/supabase/types.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
	public: {
		Tables: {
			[key: string]: {
				Row: Record<string, unknown>;
				Insert: Record<string, unknown>;
				Update: Record<string, unknown>;
			};
		};
		Views: {
			[key: string]: {
				Row: Record<string, unknown>;
			};
		};
		Functions: {
			[key: string]: {
				Args: Record<string, unknown>;
				Returns: unknown;
			};
		};
		Enums: {
			[key: string]: string;
		};
	};
}

